import os
from typing import Any, Dict, Optional


def get_database_url() -> Optional[str]:
    return os.getenv("DATABASE_URL")

def get_invoices_table() -> str:
    # Avoid clashing with existing customer schema.
    return os.getenv("INVOICES_TABLE", "aminus_invoices")


def ensure_invoices_table(conn) -> None:
    table = get_invoices_table()
    # Create table if needed
    conn.execute(
        f"""
        create table if not exists {table} (
          id bigint generated by default as identity,
          created_at timestamptz not null default now(),
          status text,
          filename text,
          pdf_path text,
          pdf_url text,
          security jsonb,
          reconciliation jsonb,
          extracted jsonb
        );
        """
    )

    # Minimal migration support if columns drift
    conn.execute(f"alter table {table} add column if not exists status text;")
    conn.execute(f"alter table {table} add column if not exists filename text;")
    conn.execute(f"alter table {table} add column if not exists pdf_path text;")
    conn.execute(f"alter table {table} add column if not exists pdf_url text;")
    conn.execute(f"alter table {table} add column if not exists security jsonb;")
    conn.execute(f"alter table {table} add column if not exists reconciliation jsonb;")
    conn.execute(f"alter table {table} add column if not exists extracted jsonb;")


def insert_invoice_row(
    *,
    status: Optional[str],
    filename: Optional[str],
    pdf_path: Optional[str],
    pdf_url: Optional[str],
    security: Dict[str, Any],
    reconciliation: Dict[str, Any],
    extracted: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Writes to Postgres using DATABASE_URL.
    """

    import psycopg

    url = get_database_url()
    if not url:
        return {"status": "stub", "reason": "DATABASE_URL not configured"}

    with psycopg.connect(url) as conn:
        with conn.cursor() as cur:
            ensure_invoices_table(cur)
            table = get_invoices_table()
            cur.execute(
                f"""
                insert into {table}(status, filename, pdf_path, pdf_url, security, reconciliation, extracted)
                values (%s, %s, %s, %s, %s::jsonb, %s::jsonb, %s::jsonb)
                returning id
                """,
                (
                    status,
                    filename,
                    pdf_path,
                    pdf_url,
                    psycopg.types.json.Jsonb(security),
                    psycopg.types.json.Jsonb(reconciliation),
                    psycopg.types.json.Jsonb(extracted),
                ),
            )
            row_id = cur.fetchone()[0]
            conn.commit()
            return {"status": "ok", "id": row_id}

